import type { CardType } from '@/models/Card.model'

export type PresetOption = {
  id?: string
  type: CardType
  category: string
  label: string
  content: string
  usageCount?: number
  meta?: Record<string, any>
}

export const VIDPROM_PRESET_OPTIONS: Record<string, PresetOption[]> = {
  "subject": [
    { type: "subject", category: "subject", label: "罗马士兵", content: "photorealistic roman soldier fighting in celtic warrior in the Scottish Highlands" },
    { type: "subject", category: "subject", label: "少年与电脑", content: "a 1982 music video clip of a basement with a teenage boy on his computer , -FPS 30" },
    { type: "subject", category: "subject", label: "动画风格", content: "MEDIUM: 3D animation, 2D animation, Cinematic Film, Animation, Cartoon" },
    { type: "subject", category: "subject", label: "城市日落的猫", content: "a golden cat on building roof , city sunset , stop motion, stop motion" },
    { type: "subject", category: "subject", label: "猫与蝴蝶", content: "a realistic video of a gray and white cat playing with a butterfly in a beautiful garden" },
    { type: "subject", category: "subject", label: "游戏手柄", content: "man picks up a gaming joystick from a shelf of a store" },
    { type: "subject", category: "subject", label: "动画动物", content: "cute anime animals dancing, cinematic shot, hand drawn" },
    { type: "subject", category: "subject", label: "日式房屋", content: "Cinematic and architectural rendering of a round oak house japanese style" },
    { type: "subject", category: "subject", label: "飞天猫", content: "cat flying over the rainbow" },
    { type: "subject", category: "subject", label: "蓝天与飞鸟", content: "White clouds are floating in the blue sky and two birds are flying" },
    { type: "subject", category: "subject", label: "人类锻炼", content: "humans doing exercises" },
    { type: "subject", category: "subject", label: "星夜螺旋", content: "a spiral of stars above the mountain in a night sky, in the style of time lapse" },
    { type: "subject", category: "subject", label: "中国女孩唱歌", content: "A 1 minute video of Real Chinese young and beautiful girls singing captured by cameras" },
    { type: "subject", category: "subject", label: "女性说话", content: "a woman is speaking" },
    { type: "subject", category: "subject", label: "女孩读书", content: "leaves falling, slowly blinking, gently turning the pages, a girl is sitting under a tree with a book" },
    { type: "subject", category: "subject", label: "艺术概念", content: "close-up, ultra detailed visually rich concept art illustration of the illusion of separateness" },
    { type: "subject", category: "subject", label: "渐变背景", content: "The background features a layered gradient, starting with cobalt blue gradually blending into teal" },
    { type: "subject", category: "subject", label: "神圣能量", content: "the loving energy that emanates from the heavens. sunlight and beauty. mystical, magical, spiritual" },
    { type: "subject", category: "subject", label: "黄色连体衣", content: "a cute little boy in yellow jumpsuit in a purple background saying something" },
    { type: "subject", category: "subject", label: "抑郁的男人", content: "Depressed 35-year-old man, sitting in front of his computer with a glass of beer" },
    { type: "subject", category: "subject", label: "艾玛的日程", content: "Picture Emma creating a detailed schedule, carefully organizing her time" },
    { type: "subject", category: "subject", label: "未来汽车", content: "synthwave style, a droid in a future car driving to the horizon, a sunset day" },
    { type: "subject", category: "subject", label: "工业贸易", content: "The future of the world is industry and cargo ship trade" },
    { type: "subject", category: "subject", label: "儿童卧室", content: "Dawn in a Child's Bedroom: Child's bedroom during sunrise" },
    { type: "subject", category: "subject", label: "罗威纳犬", content: "love story of 2 rotweiler dogs" },
    { type: "subject", category: "subject", label: "旅行广告", content: "Create a 4-second shot for a travel advertisement that encapsulates tranquility" },
    { type: "subject", category: "subject", label: "监狱守卫", content: "Low angle, A prison guard's hand opens the old solid steel door to a solitary cell" },
    { type: "subject", category: "subject", label: "秋季湖泊", content: "lake surrounded by cliffs in autumn, overdetailed art, cinematic render" },
    { type: "subject", category: "subject", label: "迪士尼男孩", content: "disney cartoon boy singing -ar 16:9" },
    { type: "subject", category: "subject", label: "金发女王", content: "Create an image of a blond long hair queen seated in a room, speaking or reflecting" }
  ],
  "action": [
    { type: "action", category: "action", label: "猫咪飞行", content: "Flying among clouds and stars, kitten Max discovered a world full of winged friends" },
    { type: "action", category: "action", label: "文字设计", content: "Use a clean and modern font for the text \"Relate Reality 101.\"" },
    { type: "action", category: "action", label: "字母行走", content: "The letter A walking in 3D and Walt Disney style -ar 16:9" },
    { type: "action", category: "action", label: "动画制作", content: "MEDIUM: 3D animation, 2D animation, Cinematic Film, Animation, Cartoon" },
    { type: "action", category: "action", label: "学生与手机", content: "a student putting his phone aside and looking around with a smile on his face" },
    { type: "action", category: "action", label: "猫扑蝴蝶", content: "a realistic video of a gray and white cat playing with a butterfly" },
    { type: "action", category: "action", label: "巴菲特的悲伤", content: "warren buffett sitting and sad on charlie munger passing away" },
    { type: "action", category: "action", label: "飞天猫", content: "cat flying over the rainbow" },
    { type: "action", category: "action", label: "飞鸟动画", content: "White clouds are floating in the blue sky and two birds are flying" },
    { type: "action", category: "action", label: "女孩唱歌", content: "A 1 minute video of Real Chinese young and beautiful girls singing" },
    { type: "action", category: "action", label: "渐变背景", content: "The background features a layered gradient, starting with cobalt blue gradually" },
    { type: "action", category: "action", label: "夜间精灵", content: "fairies flying through puppy forest at night, 4K -ar 1:1" },
    { type: "action", category: "action", label: "黄色连体衣男孩", content: "a cute little boy in yellow jumpsuit in a purple background saying something" },
    { type: "action", category: "action", label: "梵高风格斑马", content: "a Van Gogh painting of a Zebra running towards a Coca-cola bottle" },
    { type: "action", category: "action", label: "80年代幻想", content: "grainy, 80's dark fantasy, 80's movie, goblins walking in a line" },
    { type: "action", category: "action", label: "角色运动", content: "Make the background and characters move" },
    { type: "action", category: "action", label: "未来汽车", content: "synthwave style, a droid in a future car driving to the horizon" },
    { type: "action", category: "action", label: "高速摄影", content: "32k resolution, sharp, captured by Phantom High-Speed Camera" },
    { type: "action", category: "action", label: "太空旅行", content: "fast travel through space, lightspeed, imax, kodak 2383" },
    { type: "action", category: "action", label: "儿童卧室", content: "Dawn in a Child's Bedroom: Child's bedroom during sunrise" },
    { type: "action", category: "action", label: "使徒保罗", content: "apostle paul in the bible walking" },
    { type: "action", category: "action", label: "监狱门", content: "Low angle, A prison guard's hand opens the old solid steel door" },
    { type: "action", category: "action", label: "迪士尼男孩", content: "disney cartoon boy singing -ar 16:9" },
    { type: "action", category: "action", label: "金发女王", content: "Create an image of a blond long hair queen seated in a room" },
    { type: "action", category: "action", label: "雨中剪影", content: "A silhouette in a raincoat stands in the wind" },
    { type: "action", category: "action", label: "白色游艇", content: "a white yacht traveling on a river and passing under the bridge" },
    { type: "action", category: "action", label: "城堡前歌唱", content: "male music artist singing in front of a old castle while autumn leaves fall" },
    { type: "action", category: "action", label: "狮子进化", content: "evolution style picture style of a Side view profile of a lion turning into a human" },
    { type: "action", category: "action", label: "黑暗小巷", content: "guy walking in a dark alley" },
    { type: "action", category: "action", label: "杰克与吉尔", content: "Jack and Jill, two young children, walk hand in hand up a grassy hill" }
  ],
  "scene": [
    { type: "scene", category: "scene", label: "云朵与星星", content: "Flying among clouds and stars, kitten Max discovered a world full of winged friends" },
    { type: "scene", category: "scene", label: "森林暴雨", content: "a dark and ominous forest, heavy rain pouring down. Thunder rumbles in the distance" },
    { type: "scene", category: "scene", label: "魔法森林", content: "majestic bear standing amidst an enchanted forest, where trees are adorned with glowing vines" },
    { type: "scene", category: "scene", label: "动画场景", content: "MEDIUM: 3D animation, 2D animation, Cinematic Film, Animation, Cartoon" },
    { type: "scene", category: "scene", label: "大脚怪与飞船", content: "Bigfoot rides in a spaceship" },
    { type: "scene", category: "scene", label: "篝火夜晚", content: "Bonfire, relaxing time, calm space, quiet night, firelight" },
    { type: "scene", category: "scene", label: "城市日落", content: "a golden cat on building roof , city sunset , stop motion, stop motion" },
    { type: "scene", category: "scene", label: "天空中的物体", content: "Thousands of random objects falling from the sky" },
    { type: "scene", category: "scene", label: "太空漫步", content: "mac miller floating in space as a astronaut with planets spinning" },
    { type: "scene", category: "scene", label: "蓝天飞鸟", content: "White clouds are floating in the blue sky and two birds are flying" },
    { type: "scene", category: "scene", label: "深空陨石", content: "Deep space, a meteorite belt, a spaceship flew by" },
    { type: "scene", category: "scene", label: "星夜螺旋", content: "a spiral of stars above the mountain in a night sky, in the style of time lapse" },
    { type: "scene", category: "scene", label: "夜间精灵", content: "fairies flying through puppy forest at night, 4K -ar 1:1" },
    { type: "scene", category: "scene", label: "耶稣与暴雨", content: "Jesus standing in the middle of a bad rain storm in the ocean" },
    { type: "scene", category: "scene", label: "未来城市", content: "synthwave style, a droid in a future car driving to the horizon" },
    { type: "scene", category: "scene", label: "过去的低语", content: "Whispers of the Past: AI-Generated Video Unveils the Spooky Aesthetics" },
    { type: "scene", category: "scene", label: "工业未来", content: "The future of the world is industry and cargo ship trade" },
    { type: "scene", category: "scene", label: "高分辨率场景", content: "32k resolution, sharp, captured by Phantom High-Speed Camera" },
    { type: "scene", category: "scene", label: "太空旅行", content: "fast travel through space, lightspeed, imax, kodak 2383" },
    { type: "scene", category: "scene", label: "旅行广告", content: "Create a 4-second shot for a travel advertisement that encapsulates tranquility" },
    { type: "scene", category: "scene", label: "天空中的熊猫", content: "a panda floating in the sky -ar 16:9 -motion 2" },
    { type: "scene", category: "scene", label: "玉米地生长", content: "cornfield grow, cornfield show state, time sleep, in a village" },
    { type: "scene", category: "scene", label: "森林暴风雨", content: "A dark, stormy day in a clearing deep within a large and ancient forest" },
    { type: "scene", category: "scene", label: "UFO与森林", content: "a swarm of UFOs gathering over a lush forest with a monument" },
    { type: "scene", category: "scene", label: "森林小屋", content: "She resided in an old wooden cottage, and every night, she would step outside" },
    { type: "scene", category: "scene", label: "杰克与吉尔", content: "Jack and Jill, two young children, walk hand in hand up a grassy hill" },
    { type: "scene", category: "scene", label: "森林火灾", content: "The forest is on fire -fps24 -motion 6 -neg \"morphing, bad quality\"" },
    { type: "scene", category: "scene", label: "埃菲尔铁塔", content: "The Eiffel Tower sky is orange" },
    { type: "scene", category: "scene", label: "乡村善良", content: "The Village's Act of Kindness: An image of the village community coming together" },
    { type: "scene", category: "scene", label: "阿拉伯沙漠", content: "In the old times, Arab people are passing through the desert riding on horses" }
  ],
  "style": [
    { type: "style", category: "style", label: "现代字体", content: "Use a clean and modern font for the text \"Relate Reality 101.\"" },
    { type: "style", category: "style", label: "复古简约", content: "minimalist, vintage, camera, digital art" },
    { type: "style", category: "style", label: "水下世界", content: "An underwater world with realistic fish and other creatures of the sea" },
    { type: "style", category: "style", label: "写实风格", content: "photorealistic roman soldier fighting in celtic warrior" },
    { type: "style", category: "style", label: "动画风格", content: "MEDIUM: 3D animation, 2D animation, Cinematic Film, Animation, Cartoon" },
    { type: "style", category: "style", label: "幻想风格", content: "Fantasy characters from a role game of dragons entering a cave" },
    { type: "style", category: "style", label: "写实视频", content: "a realistic video of a gray and white cat playing with a butterfly" },
    { type: "style", category: "style", label: "动画艺术", content: "cute anime animals dancing, cinematic shot, hand drawn" },
    { type: "style", category: "style", label: "前卫时尚", content: "avant garde ultra realistic fashion beauty photo editorial" },
    { type: "style", category: "style", label: "动画效果", content: "leaves falling, slowly blinking, gently turning the pages" },
    { type: "style", category: "style", label: "概念艺术", content: "close-up, ultra detailed visually rich concept art" },
    { type: "style", category: "style", label: "延时摄影", content: "close up on a rose blooming in timelapse ultra realistic" },
    { type: "style", category: "style", label: "俄罗斯文字", content: "Russian tourists in restaurants Sri Lanka  Message: BKYC OCTPOBA" },
    { type: "style", category: "style", label: "高分辨率", content: "32k resolution, sharp, captured by Phantom High-Speed Camera" },
    { type: "style", category: "style", label: "低角度", content: "Low angle, A prison guard's hand opens the old solid steel door" },
    { type: "style", category: "style", label: "秋季湖泊", content: "lake surrounded by cliffs in autumn, overdetailed art, cinematic render" },
    { type: "style", category: "style", label: "迪士尼风格", content: "disney cartoon boy singing -ar 16:9" },
    { type: "style", category: "style", label: "角色展示", content: "Realistic, personality: Show a series of quick shots of Jake, Sophie, and Anna" },
    { type: "style", category: "style", label: "1960年代", content: "A vintage 1960 movie footage of a couple of cowboys riding horses" },
    { type: "style", category: "style", label: "女战士", content: "warrior princess sitting on a throne, people kneeling before her" },
    { type: "style", category: "style", label: "卡通燃烧", content: "strange and cool cartoon clip, burning cross" },
    { type: "style", category: "style", label: "星夜动画", content: "Ethereal Starlit Night. Panning. Anime art animation. --ar 9:16" },
    { type: "style", category: "style", label: "复古电视", content: "vintage television with static" },
    { type: "style", category: "style", label: "地球重生", content: "Generate a video depicting the recreation of Earth" },
    { type: "style", category: "style", label: "赛博朋克", content: "A body at a Night event party. Multicultural European Asian solarpunk avatar" },
    { type: "style", category: "style", label: "细节特写", content: "extreme details of erupting tiny yellow egg yolks with sparkling black caviar" },
    { type: "style", category: "style", label: "真实树木", content: "trees wind, realistic, Show the sun rising over the mountains" },
    { type: "style", category: "style", label: "游戏风格", content: "Minecraft vs roblox, cartoon characters, vibrant colors" },
    { type: "style", category: "style", label: "乡村生活", content: "A man was living in village he used to cut woods for his living" }
  ],
  "camera": [
    // 摄像机移动
    { type: "camera", category: "camera", label: "推镜拍摄", content: "Dolly shot" },
    { type: "camera", category: "camera", label: "跟踪拍摄", content: "Tracking shot" },
    { type: "camera", category: "camera", label: "俯拍镜头", content: "Crane shot" },
    { type: "camera", category: "camera", label: "鸟瞰图", content: "Aerial view" },
    { type: "camera", category: "camera", label: "缓慢推镜", content: "Slow pan" },
    { type: "camera", category: "camera", label: "视角镜头", content: "POV shot" },
    
    // 构图
    { type: "camera", category: "camera", label: "广角镜头", content: "Wide shot" },
    { type: "camera", category: "camera", label: "特写镜头", content: "Close-up" },
    { type: "camera", category: "camera", label: "极近距离特写", content: "Extreme close-up" },
    { type: "camera", category: "camera", label: "低角度", content: "Low angle" },
    { type: "camera", category: "camera", label: "两发子弹", content: "Two-shot" },
    
    // 镜头与焦距
    { type: "camera", category: "camera", label: "浅景深效果", content: "Shallow depth of field" },
    { type: "camera", category: "camera", label: "广角镜头", content: "Wide-angle lens" },
    { type: "camera", category: "camera", label: "柔焦效果", content: "Soft focus" },
    { type: "camera", category: "camera", label: "微距镜头", content: "Macro lens" },
    { type: "camera", category: "camera", label: "深度聚焦", content: "Deep focus" },
    { type: "camera", category: "camera", label: "动画动物", content: "cute anime animals dancing, cinematic shot, hand drawn" },
    { type: "camera", category: "camera", label: "湿婆特写", content: "cinematic depiction of lord shiva, close up, mountain view wide angle, surreal" },
    { type: "camera", category: "camera", label: "概念艺术", content: "close-up, ultra detailed visually rich concept art illustration of the illusion of separateness" },
    { type: "camera", category: "camera", label: "热牛奶准备", content: "Show the preparation of a glass of hot milk with turmeric. The camera captures the process" },
    { type: "camera", category: "camera", label: "旅行广告", content: "Create a 4-second shot for a travel advertisement that encapsulates tranquility" },
    { type: "camera", category: "camera", label: "监狱门", content: "Low angle, A prison guard's hand opens the old solid steel door to a solitary cell" },
    { type: "camera", category: "camera", label: "角色展示", content: "Realistic, personality: Show a series of quick shots of Jake, Sophie, and Anna" },
    { type: "camera", category: "camera", label: "戴森球", content: "3-shot cinematic film clip of alien Dyson sphere failing, collapsing planetary system" },
    { type: "camera", category: "camera", label: "星球全景", content: "A breathtaking panoramic view of the unique planet Veridian Prime, its vibrant vegetation" },
    { type: "camera", category: "camera", label: "角色设计", content: "a girl with short yellow hair, white dress and red shoes character sheet, multiple poses" },
    { type: "camera", category: "camera", label: "白马奔跑", content: "a video where a white horse is running in a green river field for 6 seconds" },
    { type: "camera", category: "camera", label: "品牌展示", content: "The 'Catalano Office' brand elegantly appears on the screen" },
    { type: "camera", category: "camera", label: "青年特写", content: "close-up wide shot, centered, daytime, an 18 year old young man with spiky white hair" },
    { type: "camera", category: "camera", label: "猫咪花园", content: "A white and orange tabby cat happily walks through a lush garden, as if chasing something" },
    { type: "camera", category: "camera", label: "城市介绍", content: "A serene shot of Excellenceburg, with a soft voiceover introducing Richard" },
    { type: "camera", category: "camera", label: "老人公园", content: "Shot: An elderly man sits in a black and white park, covering his ear with his hand" },
    { type: "camera", category: "camera", label: "盲人行走", content: "acrylic people walking around with their eyes closed groping. hyper realistic" },
    { type: "camera", category: "camera", label: "外星飞船", content: "wide shot, front shot, centered, daytime, an alien spaceship Haunebu III flying" },
    { type: "camera", category: "camera", label: "时尚女性", content: "in white background, a fashion hot brunette woman with futuristic eyeglasses" },
    { type: "camera", category: "camera", label: "精灵视角", content: "Photorealistic elven female pov from above, gigantic blue eyes, blonde hair" },
    { type: "camera", category: "camera", label: "未来人类", content: "wide angle shot, front view, centered, daytime, a man with red hair and futuristic glasses" },
    { type: "camera", category: "camera", label: "太空殖民", content: "A colonist on his ship, ships in background, Full shot, erratic fluctuation in motion" },
    { type: "camera", category: "camera", label: "学校操场", content: "A school playground -wide shot -far away -30fps -dramatic -cinematic -realistic" },
    { type: "camera", category: "camera", label: "动态场景", content: "maximum movement, frame by frame animation, dynamic scene, cinematic shot" },
    { type: "camera", category: "camera", label: "无人机森林", content: "a fleet of drones flies through a dense forest -motion 2 -ar 16:9" },
    { type: "camera", category: "camera", label: "城市洪水", content: "tilt camera , action shot , huge flood with big waves flooding a city , post apocalyptic" },
    { type: "camera", category: "camera", label: "墨西哥丛林", content: "The Mexican jungle and village are teeming with life. Plants and animals abound" },
    { type: "camera", category: "camera", label: "音乐几何", content: "Theme: Modern, minimalist, geometric shapes with musical references. Color palette: pale blues and grays" },
    { type: "camera", category: "camera", label: "镀铬螺旋", content: "UHD 8K 4K extreme hyper realistic action angle spiraling through a chrome circular tunnel" },
    { type: "camera", category: "camera", label: "孩子飞天", content: "Close-up of children soaring up into the sky above a field in summer, Synthwave style" }
  ],
  "lighting": [
    { type: "lighting", category: "lighting", label: "森林暴雨", content: "a dark and ominous forest, heavy rain pouring down. Thunder rumbles in the distance" },
    { type: "lighting", category: "lighting", label: "篝火夜晚", content: "Bonfire, relaxing time, calm space, quiet night, firelight" },
    { type: "lighting", category: "lighting", label: "猫咪花园", content: "a realistic video of a gray and white cat playing with a butterfly in a beautiful garden" },
    { type: "lighting", category: "lighting", label: "戏剧风格", content: "Stylization: drama. A young guy in jeans and a green bomber jacket is covered in blood" },
    { type: "lighting", category: "lighting", label: "黑暗思考", content: "thinking about the dark side" },
    { type: "lighting", category: "lighting", label: "概念艺术", content: "close-up, ultra detailed visually rich concept art illustration of the illusion of separateness" },
    { type: "lighting", category: "lighting", label: "渐变背景", content: "The background features a layered gradient, starting with cobalt blue gradually blending into teal" },
    { type: "lighting", category: "lighting", label: "神圣能量", content: "the loving energy that emanates from the heavens. sunlight and beauty. mystical, magical, spiritual" },
    { type: "lighting", category: "lighting", label: "克利奥帕特拉", content: "Generate images representing the debated legacy of Cleopatra. Show historians engaging in discussion" },
    { type: "lighting", category: "lighting", label: "抑郁的男人", content: "Depressed 35-year-old man, sitting in front of his computer with a glass of beer" },
    { type: "lighting", category: "lighting", label: "海上爆炸", content: "huge explosion above sea. hurricane. tsunami. Rainy . dark dystopian cinematic scene" },
    { type: "lighting", category: "lighting", label: "80年代幻想", content: "grainy, 80's dark fantasy, 80's movie, goblins walking in a line down a dark forest path" },
    { type: "lighting", category: "lighting", label: "高分辨率", content: "32k resolution, sharp, captured by Phantom High-Speed Camera hyper realistic white" },
    { type: "lighting", category: "lighting", label: "太空旅行", content: "fast travel through space, lightspeed, imax, kodak 2383, camera movement -ar 16:9" },
    { type: "lighting", category: "lighting", label: "热牛奶准备", content: "Show the preparation of a glass of hot milk with turmeric. The camera captures the process" },
    { type: "lighting", category: "lighting", label: "旅行广告", content: "Create a 4-second shot for a travel advertisement that encapsulates the tranquility" },
    { type: "lighting", category: "lighting", label: "监狱门", content: "Low angle, A prison guard's hand opens the old solid steel door to a solitary cell" },
    { type: "lighting", category: "lighting", label: "街灯阴影", content: "A customer with a shadow covering his face under the dim light of a street lamp" },
    { type: "lighting", category: "lighting", label: "1960年代", content: "A vintage 1960 movie footage of a couple of cowboys riding horses, tall, thin, black" },
    { type: "lighting", category: "lighting", label: "哥特城堡", content: "Mysterious Gothic castle, many towers, top view, technological atmosphere, futuristic" },
    { type: "lighting", category: "lighting", label: "森林暴风雨", content: "A dark, stormy day in a clearing deep within a large and ancient forest. The clouds are dark and ominous" },
    { type: "lighting", category: "lighting", label: "黑暗小巷", content: "guy walking in a dark alley" },
    { type: "lighting", category: "lighting", label: "杰克与吉尔", content: "Jack and Jill, two young children, walk hand in hand up a grassy hill towards a house" },
    { type: "lighting", category: "lighting", label: "全息鱼", content: "POV, a fish wearing a dress walking down the street, Holographic 3D Style -neg 'bad quality'" },
    { type: "lighting", category: "lighting", label: "教堂内部", content: "amazing view inside cathedral, yellow light-camera zoom out" },
    { type: "lighting", category: "lighting", label: "夜晚派对", content: "A body at a Night event party . Multicultural European Asian solarpunk avatar with neon lights" },
    { type: "lighting", category: "lighting", label: "哥特式街灯", content: "In a still frame, in the picturesque square, a Gothic-style lamppost adorned with" },
    { type: "lighting", category: "lighting", label: "鸡蛋细节", content: "extreme details of erupting tiny yellow egg yolks with sparkling black caviar and" },
    { type: "lighting", category: "lighting", label: "黑暗森林中的猫", content: "Cutest cat with golden blue eyes in the dark forest with pack of popcorn and tv watching" },
    { type: "lighting", category: "lighting", label: "沙漠中的城堡", content: "castle in the middle of the desert, cosmic spectacle, late night, foggy atmosphere" }
  ],
  "audio": [
    { type: "audio", category: "audio", label: "猫咪飞行", content: "Flying among clouds and stars, kitten Max discovered a world full of winged friends" },
    { type: "audio", category: "audio", label: "森林暴雨", content: "a dark and ominous forest, heavy rain pouring down. Thunder rumbles in the distance" },
    { type: "audio", category: "audio", label: "魔法森林", content: "majestic bear standing amidst an enchanted forest, where trees are adorned with glowing vines" },
    { type: "audio", category: "audio", label: "银色机器人", content: "silver metallic robots at walmart, night -ar 16:9" },
    { type: "audio", category: "audio", label: "篝火夜晚", content: "Bonfire, relaxing time, calm space, quiet night, firelight" },
    { type: "audio", category: "audio", label: "中国女孩唱歌", content: "A 1 minute video of Real Chinese young and beautiful girls singing captured by cameras" },
    { type: "audio", category: "audio", label: "抑郁的男人", content: "depressed 35-year-old man, sitting in front of his computer with a glass of beer" },
    { type: "audio", category: "audio", label: "黑暗思考", content: "thinking about the dark side" },
    { type: "audio", category: "audio", label: "海上爆炸", content: "huge explosion above sea. hurricane. tsunami. Rainy . dark dystopian cinematic scene" },
    { type: "audio", category: "audio", label: "大声快速", content: "make the audio loud and fast" },
    { type: "audio", category: "audio", label: "男人与电脑", content: "depressed 35-year-old man, sitting in front of his computer with a glass of beer" },
    { type: "audio", category: "audio", label: "冻结时间", content: "a laptop, frozen in time -seed 5766880 -motion 0" }
  ],
  "constraint": [
    { type: "constraint", category: "constraint", label: "森林暴雨", content: "a dark and ominous forest, heavy rain pouring down. Thunder rumbles in the distance" },
    { type: "constraint", category: "constraint", label: "概念艺术", content: "close-up, ultra detailed visually rich concept art illustration of the illusion of separateness" },
    { type: "constraint", category: "constraint", label: "高分辨率", content: "32k resolution, sharp, captured by Phantom High-Speed Camera hyper realistic white" },
    { type: "constraint", category: "constraint", label: "太空上帝", content: "faça uma imagem de Deus no espaço criando estrelas 19:6" },
    { type: "constraint", category: "constraint", label: "1960年代西部", content: "A vintage 1960 movie footage of a couple of cowboys riding horses, tall, thin, black" },
    { type: "constraint", category: "constraint", label: "哥特城堡", content: "Mysterious Gothic castle, many towers, top view, technological atmosphere, futuristic" },
    { type: "constraint", category: "constraint", label: "森林火灾", content: "The forest is on fire -fps24 -motion 6 -neg \"morphing, bad quality, distortion\"" },
    { type: "constraint", category: "constraint", label: "CEO团队", content: "ceo Lupita Nyong'o with long red hair, ceo Latino James Marsden and ceo Chic" },
    { type: "constraint", category: "constraint", label: "驾驶学校", content: "Yes, within a year after completing studies at a driving school and receiving a" },
    { type: "constraint", category: "constraint", label: "乡村善良", content: "The Village's Act of Kindness: An image of the village community coming together" },
    { type: "constraint", category: "constraint", label: "游戏角色", content: "The Division 2, agent in red jacket and black cap, the agent stands in the center" },
    { type: "constraint", category: "constraint", label: "星球全景", content: "A breathtaking panoramic view of the unique planet Veridian Prime, its vibrant vegetation" },
    { type: "constraint", category: "constraint", label: "沙漠城堡", content: "castle in the middle of the desert, cosmic spectacle, late night, foggy atmosphere" },
    { type: "constraint", category: "constraint", label: "乡村生活", content: "A man was living in village he used to cut woods for his living one day he was" },
    { type: "constraint", category: "constraint", label: "品牌展示", content: "The \"Catalano Office\" brand elegantly appears on the screen, with the" },
    { type: "constraint", category: "constraint", label: "青年特写", content: "close-up wide shot, centered, daytime, an 18 year old young man with spiky white hair" },
    { type: "constraint", category: "constraint", label: "木屋圣诞", content: "wood cabin living room with a christmas tree and a working fireplace with big fire" },
    { type: "constraint", category: "constraint", label: "量子朋克", content: "Quantum Steampunk Cityscape biological female goddess, Extreme Hyper realistic" },
    { type: "constraint", category: "constraint", label: "盲人行走", content: "acrylic people walking around with their eyes closed groping. hyper realistic" },
    { type: "constraint", category: "constraint", label: "恋爱中的女孩", content: "Beautiful girl, Mind not under control, completely in love" },
    { type: "constraint", category: "constraint", label: "时尚女性", content: "in white background, a fashion hot brunette woman with futuristic eyeglasses" },
    { type: "constraint", category: "constraint", label: "精灵视角", content: "Photorealistic elven female pov from above, gigantic blue eyes, blonde hair, natural" },
    { type: "constraint", category: "constraint", label: "未来人类", content: "wide angle shot, front view, centered, daytime, a man with red hair and futuristic glasses" },
    { type: "constraint", category: "constraint", label: "太空殖民", content: "A colonist on his ship, ships in background, Full shot, erratic fluctuation in motion" },
    { type: "constraint", category: "constraint", label: "数据科技", content: "data technology futuristic illustration with spectacular waves of bright particles" },
    { type: "constraint", category: "constraint", label: "浪漫告白", content: "\"Orsino and Viola's Confession\": The romantic confession between Orsino and Viola" },
    { type: "constraint", category: "constraint", label: "黄色头发青年", content: "front view wide, centered, daytime, an 18 year old young man with spiky yellow hair" },
    { type: "constraint", category: "constraint", label: "绵羊饮水", content: "sheeps drinking water from a stream, NATURAL LIGHT, 4K photography, 50mm f/1.8 lens" },
    { type: "constraint", category: "constraint", label: "FNAF场景", content: "foxy from fnaf1 micromotions cinematic scene forward zooming tilt camera, 16K, motion" }
  ]
}
